# Generated by Django 5.1.2 on 2024-11-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermod',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.RemoveField(
            model_name='usermod',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usermod',
            name='user_name',
        ),
    ]
