# Generated by Django 5.1.2 on 2024-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usermod_options_remove_usermod_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermod',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='usermod',
            name='full_name',
            field=models.CharField(default=2, max_length=150, verbose_name='full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermod',
            name='user_id',
            field=models.PositiveBigIntegerField(default=2, verbose_name='telegram id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermod',
            name='user_name',
            field=models.CharField(default=2, max_length=100, verbose_name='username'),
            preserve_default=False,
        ),
    ]
