# Generated by Django 5.1.2 on 2025-03-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usermod_options_usermod_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(verbose_name='telegram id')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='foydalanuvchi ism')),
                ('full_name', models.CharField(max_length=150, verbose_name="to'liq ism")),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Adminlar',
            },
        ),
        migrations.CreateModel(
            name='GroupMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.PositiveBigIntegerField(verbose_name='guruh/kanal id')),
                ('group_name', models.CharField(max_length=150, verbose_name='guruh/kanal nomi')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='InlineButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='tugma matni')),
                ('text_response', models.CharField(max_length=100, verbose_name='tugma bosilganda')),
                ('is_correct', models.BooleanField(default=False, verbose_name="to'g'ri / hato")),
                ('static', models.BooleanField(default=False, verbose_name='static')),
            ],
            options={
                'verbose_name': 'Tugma',
                'verbose_name_plural': 'Tugmalar',
            },
        ),
        migrations.AlterField(
            model_name='usermod',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name="to'liq ism"),
        ),
        migrations.AlterField(
            model_name='usermod',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='foydalanuvchi ism'),
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='xabar matni')),
                ('to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groupmod', verbose_name='guruh/kanal')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
    ]
