# Generated by Django 5.1.2 on 2025-03-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_adminmod_groupmod_inlinebutton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinebutton',
            name='bot_message',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.botmessage', verbose_name='savol'),
            preserve_default=False,
        ),
    ]
