# Generated by Django 5.1.7 on 2025-03-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_inlinebutton_bot_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inlinebutton',
            options={'ordering': ['id'], 'verbose_name': 'Tugma', 'verbose_name_plural': 'Tugmalar'},
        ),
    ]
