# Generated by Django 5.1.7 on 2025-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_inlinebutton_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmod',
            name='group_id',
            field=models.BigIntegerField(verbose_name='guruh/kanal id'),
        ),
    ]
