# Generated by Django 5.1.7 on 2025-04-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_botmessage_to_group_botmessage_to_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmod',
            options={'verbose_name': 'Guruh / Kanal', 'verbose_name_plural': 'Guruhlar / Kanallar'},
        ),
        migrations.AddField(
            model_name='inlinebutton',
            name='row',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='to_group',
            field=models.ManyToManyField(related_name='manzillar', to='main.groupmod', verbose_name='manzil'),
        ),
        migrations.AlterField(
            model_name='groupmod',
            name='group_id',
            field=models.BigIntegerField(verbose_name='guruh / kanal id'),
        ),
        migrations.AlterField(
            model_name='groupmod',
            name='group_name',
            field=models.CharField(max_length=150, verbose_name='guruh / kanal nomi'),
        ),
        migrations.AlterField(
            model_name='inlinebutton',
            name='bot_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='main.botmessage', verbose_name='savol'),
        ),
        migrations.AlterField(
            model_name='inlinebutton',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name="to'g'ri"),
        ),
    ]
