# Generated by Django 5.1.7 on 2025-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_groupmod_options_inlinebutton_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinebutton',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
