# Generated by Django 5.1.7 on 2025-04-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_inlinebutton_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='rasm'),
        ),
    ]
