# Generated by Django 5.1.7 on 2025-04-03 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_botmessage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlinebutton',
            name='position',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='raqam'),
        ),
        migrations.AlterField(
            model_name='inlinebutton',
            name='row',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='qator'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='telegram id')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='foydalanuvchi ism')),
                ('group_id', models.BigIntegerField(verbose_name='guruh / kanal id')),
                ('is_correct', models.BooleanField(verbose_name="to'g'ri")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vaqt')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inlinebutton', verbose_name='tugma')),
            ],
        ),
    ]
