# Generated by Django 5.1.7 on 2025-04-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_inlinebutton_position_alter_inlinebutton_row_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Javob', 'verbose_name_plural': 'Javoblar'},
        ),
    ]
