# Generated by Django 5.1.7 on 2025-04-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_useranswer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inlinebutton',
            name='static',
        ),
        migrations.AddField(
            model_name='botmessage',
            name='static',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='static'),
        ),
    ]
